/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
    darkMode: 'class',
    theme: {
      extend: {
        scale: {
          125: '1.25',
        },
        spacing: {
          '30p': '30px',
          '70p': '70px',
        },
        height: {
          128: '32rem',
          '80screen': '80vh',
          '0.5font': '0.5em',
          '0.8font': '0.8em',
          '90screen': '90vh',
          font: '1em',
          '60vw': '60vw',
          'asp-xl': '21rem',
          'asp-2xl': '24rem',
          'asp-3xl': '28rem',
          'asp-4xl': '32rem',
        },
        boxShadow: {
          nav: '0px 0px 10px 0px rgba(0, 0, 0, 0.5)',
        },
        transitionProperty: {
          top: 'top',
        },
        maxHeight: {
          '70screen': '70vh',
          '80screen': '80vh',
          screen: '100vh',
          '90screen': '90vh',
          '10screen': '10vh',
        },
        margin: {
          '10vh': '10vh',
        },
        width: {
          '80screen': '80vw',
          '70screen': '70vw',
          '60screen': '60vw',
          font: '1em',
          '0.5font': '0.5em',
          '0.8font': '0.8em',
          95: '95%',
          xl: '36rem',
          '2xl': '42rem',
          '3xl': '48rem',
          '4xl': '56rem',
        },
        zIndex: {
          60: '60',
          70: '70',
          nav: '55',
          'nav-1': '1001',
          'nav-2': '1002',
          'nav-3': '1003',
          'nav-4': '1004',
        },
        divideWidth: {
          1: '1px',
        },
        minWidth: {
          '1/4': '25%',
          '1/2': '50%',
          '3/4': '75%',
          95: '95%',
          '95screen': '95vw',
          sm: '640px',
          '2screen': '200vw',
        },
        maxWidth: {
          '1/4': '25%',
          '1/2': '50%',
          '3/4': '75%',
          95: '95%',
          screen: '100vw',
          '95screen': '95vw',
          '80screen': '80vw',
          36: '144px',
          96: '384px',
        },
        minHeight: {
          '80screen': '80vh',
          '60screen': '60vh',
          screen: '100vh',
          48: '192px',
        },
        listStyleType: {
          none: 'none',
          disc: 'disc',
          decimal: 'decimal',
          square: 'square',
          roman: 'upper-roman',
          circle: 'circle',
        },
        backgroundSize: {
          auto: 'auto',
          cover: 'cover',
          contain: 'contain',
          full: '100%',
        },
        transitionProperty: {
          'bg-size': 'background-size',
        },
      },
    },
    plugins: [],
  };